import React from "react";

const Term = () => {
  return (
    <div className="max-w-[1600px] mx-0 my-auto px-0 py-0 w-[100%] ">
      <div className="w-full flex justify-center items-center mt-40 px-4 sm:px-32 py-3">
        <div className="w-full flex flex-col justify-start items-start">
          <h2 className="text-xl md:text-2xl leading-2 font-bold mb-4">
            Terms of Service
          </h2>
          <h4 className="text-base leading-6 font-semibold mb-4">
            {" "}
            Agreement between User and www.pegam.ai
          </h4>
          <p className="text-base leading-6  mb-4">
            Welcome to www.pegam.ai. The www.pegam.ai website (the "Site") is
            comprised of various web pages operated by Pegam Inc. ("Pegam").
            www.pegam.ai is offered to you conditioned on your acceptance
            without modification of the terms, conditions, and notices contained
            herein (the "Terms"). Your use of www.pegam.ai constitutes your
            agreement to all such Terms. Please read these terms carefully, and
            keep a copy of them for your reference.
          </p>

          <p className="text-base leading-6  mb-4">
            www.pegam.ai is a Physical Mail Automation Platform. Pegam's goal is
            to help enterprises unlock a profitable new growth channel and
            maximize ROI with our intelligent and personalized direct mail
            solution.
          </p>
          <h4 className="text-base leading-6 font-semibold mb-4"> Privacy</h4>

          <p className="text-base leading-6  mb-4">
            Your use of www.pegam.ai is subject to Pegam's Privacy Policy.
            Please review our Privacy Policy, which also governs the Site and
            informs users of our data collection practices.{" "}
          </p>

          <h4 className="text-base leading-6 font-semibold mb-4">
            {" "}
            Communications
          </h4>

          <p className="text-base leading-6  mb-4">
            Visiting www.pegam.ai or sending emails to Pegam constitutes
            electronic communications. You consent to receive electronic
            communications and you agree that all agreements, notices,
            disclosures, and other communications that we provide to you
            electronically, via email and on the Site, satisfy any legal
            requirement that such communications be in writing.
          </p>
          <p className="text-base leading-6  mb-4">
            By entering into this Agreement or using Pegam, you agree to receive
            communications from us or communications related to Pegam at any of
            the phone numbers provided to Pegam by you or on your behalf,
            including via e-mail, text message, calls, and push notifications.
            You agree that texts, calls, or prerecorded messages may be
            generated by automatic telephone dialing systems. Communications
            from Pegam may include but are not limited to: operational
            communications concerning your User account, status updates about a
            campaign, updates concerning new and existing features,
            communications concerning marketing or promotions run by us or our
            third-party partners, and news concerning Pegam and industry
            developments. If you change or deactivate the phone number you
            provided to Pegam, you agree to update your account information to
            help prevent us from inadvertently communicating with anyone who
            acquires your old number. Standard text messaging charges applied by
            your cell phone carrier will apply to text messages we send.
          </p>
          <p className="text-base leading-6  mb-4">
            IF YOU WISH TO OPT OUT OF PROMOTIONAL EMAILS, YOU CAN UNSUBSCRIBE
            FROM OUR PROMOTIONAL EMAIL LIST BY FOLLOWING THE UNSUBSCRIBE OPTIONS
            IN THE PROMOTIONAL EMAIL ITSELF. IF YOU WISH TO OPT OUT OF
            PROMOTIONAL TEXTS, YOU MAY TEXT “STOP” FROM THE MOBILE DEVICE
            RECEIVING THE MESSAGES.
          </p>
          <h4 className="text-base leading-6 font-semibold mb-4">
            {" "}
            Links to Third Party Sites/Third Party Services
          </h4>

          <p className="text-base leading-6  mb-4">
            www.pegam.ai may contain links to other websites ("Linked Sites").
            The Linked Sites are not under the control of Pegam and Pegam is not
            responsible for the contents of any Linked Site, including without
            limitation any link contained in a Linked Site, or any changes or
            updates to a Linked Site. Pegam is providing these links to you only
            as a convenience, and the inclusion of any link does not imply
            endorsement by Pegam of the site or any association with its
            operators. Certain services made available via www.pegam.ai are
            delivered by third-party sites and organizations. By using any
            product, service, or functionality originating from the www.pegam.ai
            domain, you hereby acknowledge and consent that Pegam may share such
            information and data with any third party with whom Pegam has a
            contractual relationship to provide the requested product, service,
            or functionality on behalf of www.pegam.ai users and customers.
          </p>
          <h4 className="text-base leading-6 font-semibold mb-4">
            {" "}
            No Unlawful or Prohibited Use/Intellectual Property
          </h4>

          <p className="text-base leading-6  mb-4">
            You are granted a non-exclusive, non-transferable, revocable license
            to access and use www.pegam.ai strictly in accordance with these
            terms of use. As a condition of your use of the Site, you warrant to
            Pegam that you will not use the Site for any purpose that is
            unlawful or prohibited by these Terms. You may not use the Site in
            any manner which could damage, disable, overburden, or impair the
            Site or interfere with any other party's use and enjoyment of the
            Site. You may not obtain or attempt to obtain any materials or
            information through any means not intentionally made available or
            provided for through the Site. All content included as part of the
            Service, such as text, graphics, logos, images, as well as the
            compilation thereof, and any software used on the Site, is the
            property of Pegam or its suppliers and protected by copyright and
            other laws that protect intellectual property and proprietary
            rights. You agree to observe and abide by all copyright and other
            proprietary notices, legends or other restrictions contained in any
            such content and will not make any changes thereto. You will not
            modify, publish, transmit, reverse engineer, participate in the
            transfer or sale, create derivative works, or in any way exploit any
            of the content, in whole or in part, found on the Site. Pegam
            content is not for resale. Your use of the Site does not entitle you
            to make any unauthorized use of any protected content, and in
            particular, you will not delete or alter any proprietary rights or
            attribution notices in any content. You will use protected content
            solely for your personal use and will make no other use of the
            content without the express written permission of Pegam and the
            copyright owner. You agree that you do not acquire any ownership
            rights in any protected content. We do not grant you any licenses,
            express or implied, to the intellectual property of Pegam or our
            licensors except as expressly authorized by these Terms.
          </p>
          <h4 className="text-base leading-6 font-semibold mb-4">
            {" "}
            Use of Communication Services
          </h4>

          <p className="text-base leading-6  mb-4">
            The Site may contain posting services, messaging functionality,
            groups, forums, communities, personal URL creation, calendars,
            and/or other message or communication facilities designed to enable
            you to communicate with the public at large or with a group
            (collectively, "Communication Services"). You agree to use the
            Communication Services only to post, send, and receive messages and
            material that are proper and related to the particular Communication
            Service. By way of example, and not as a limitation, you agree that
            when using a Communication Service, you will not: defame, abuse,
            harass, stalk, threaten or otherwise violate the legal rights (such
            as rights of privacy and publicity) of others; publish, post,
            upload, distribute or disseminate any inappropriate, profane,
            defamatory, infringing, obscene, indecent or unlawful topic, name,
            material or information; upload files that contain software or other
            material protected by intellectual property laws (or by rights of
            privacy of publicity) unless you own or control the rights thereto
            or have received all necessary consents; upload files that contain
            viruses, corrupted files, or any other similar software or programs
            that may damage the operation of another's computer; advertise or
            offer to sell or buy any goods or services for any business purpose,
            unless such Communication Service specifically allows such messages;
            conduct or forward surveys, contests, pyramid schemes, or chain
            letters; download any file posted by another user of a Communication
            Service that you know, or reasonably should know, cannot be legally
            distributed in such manner; falsify or delete any author
            attributions, legal or other proper notices or proprietary
            designations or labels of the origin or source of software or other
            material contained in a file that is uploaded; restrict or inhibit
            any other user from using and enjoying the Communication Services;
            violate any code of conduct or other guidelines which may be
            applicable for any particular Communication Service; harvest or
            otherwise collect information about others, including email
            addresses, without their consent; violate any applicable laws or
            regulations. Pegam has no obligation to monitor the Communication
            Services. However, Pegam reserves the right to review materials
            posted to a Communication Service and to remove any materials in its
            sole discretion. Pegam reserves the right to terminate your access
            to any or all of the Communication Services at any time without
            notice for any reason whatsoever. Pegam reserves the right at all
            times to disclose any information as necessary to satisfy any
            applicable law, regulation, legal process, or governmental request,
            or to edit, refuse to post, or to remove any information or
            materials, in whole or in part, in Pegam's sole discretion. Always
            use caution when giving out any personally identifying information
            about yourself or your children in any Communication Service. Pegam
            does not control or endorse the content, messages, or information
            found in any Communication Service and, therefore, Pegam
            specifically disclaims any liability with regard to the
            Communication Services and any actions resulting from your
            participation in any Communication Service. Managers and hosts are
            not authorized Pegam spokespersons, and their views do not
            necessarily reflect those of Pegam. Materials uploaded to a
            Communication Service may be subject to posted limitations on usage,
            reproduction, and/or dissemination. You are responsible for adhering
            to such limitations if you upload the materials.
          </p>
          <h4 className="text-base leading-6 font-semibold mb-4">
            {" "}
            Materials Provided to www.pegam.ai or Posted on Any Pegam Web Page
          </h4>

          <p className="text-base leading-6  mb-4">
            Pegam does not claim ownership of the materials you provide to
            www.pegam.ai (including feedback and suggestions) or post, upload,
            input, or submit to any Pegam Site or our associated services
            (collectively "Submissions"). However, by posting, uploading,
            inputting, providing, or submitting your Submission you are granting
            Pegam, our affiliated companies and necessary sublicensees
            permission to use your Submission in connection with the operation
            of their Internet businesses including, without limitation, the
            rights to: copy, distribute, transmit, publicly display, publicly
            perform, reproduce, edit, translate and reformat your Submission;
            and to publish your name in connection with your Submission. No
            compensation will be paid with respect to the use of your
            Submission, as provided herein. Pegam is under no obligation to post
            or use any Submission you may provide and may remove any Submission
            at any time in Pegam's sole discretion. By posting, uploading,
            inputting, providing, or submitting your Submission you warrant and
            represent
          </p>
        </div>
      </div>
    </div>
  );
};

export default Term;
